# Generated by Django 5.2.5 on 2025-09-29 10:18

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_type_name', models.CharField(max_length=50, unique=True, verbose_name='Название типа ответа')),
                ('answer_type_description', models.TextField(blank=True, null=True, verbose_name='Описание типа ответа')),
            ],
            options={
                'db_table': 'answer_type',
                'verbose_name': 'Тип ответа',
                'verbose_name_plural': 'Типы ответов',
            },
        ),
        migrations.CreateModel(
            name='AssignmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_status_name', models.CharField(max_length=255, unique=True, verbose_name='Название статуса задания')),
            ],
            options={
                'db_table': 'assignment_status',
                'verbose_name': 'Статус задания',
                'verbose_name_plural': 'Статусы заданий',
            },
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_category_name', models.CharField(max_length=255, verbose_name='Название категории курса')),
            ],
            options={
                'db_table': 'course_category',
                'verbose_name': 'Категория курса',
                'verbose_name_plural': 'Категории курсов',
            },
        ),
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type_name', models.CharField(max_length=255, verbose_name='Название типа курса')),
                ('course_type_description', models.TextField(blank=True, null=True, verbose_name='Описание типа курса')),
            ],
            options={
                'db_table': 'course_type',
                'verbose_name': 'Тип курса',
                'verbose_name_plural': 'Типы курсов',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=255, unique=True, verbose_name='Название роли')),
            ],
            options={
                'db_table': 'role',
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Подтверждён')),
                ('profile_theme', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цветовая тема приложения пользователя')),
                ('educational_institution', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фото профиля')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unireax_main.role', verbose_name='Роль')),
            ],
            options={
                'db_table': 'user',
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255, verbose_name='Название курса')),
                ('course_description', models.TextField(blank=True, null=True, verbose_name='Описание курса')),
                ('course_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена курса')),
                ('course_photo_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='Путь к фото курса')),
                ('has_certificate', models.BooleanField(default=False, verbose_name='Есть сертификат')),
                ('course_max_places', models.IntegerField(blank=True, null=True, verbose_name='Максимум мест')),
                ('course_hours', models.IntegerField(verbose_name='Количество часов')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершён')),
                ('code_room', models.CharField(blank=True, max_length=255, null=True, verbose_name='Код комнаты')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создан пользователем')),
                ('course_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unireax_main.coursecategory', verbose_name='Категория курса')),
                ('course_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unireax_main.coursetype', verbose_name='Тип курса')),
            ],
            options={
                'db_table': 'course',
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_name', models.CharField(max_length=255, verbose_name='Название лекции')),
                ('lecture_content', models.TextField(verbose_name='Содержание лекции')),
                ('lecture_document_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='Путь к документу лекции')),
                ('lecture_order', models.IntegerField(verbose_name='Порядок лекции')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unireax_main.course', verbose_name='Курс')),
            ],
            options={
                'db_table': 'lecture',
                'verbose_name': 'Лекция',
                'verbose_name_plural': 'Лекции',
            },
        ),
        migrations.CreateModel(
            name='PracticalAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practical_assignment_name', models.CharField(max_length=255, verbose_name='Название задания')),
                ('practical_assignment_description', models.TextField(verbose_name='Описание задания')),
                ('assignment_document_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='Путь к документу задания')),
                ('assignment_criteria', models.TextField(blank=True, null=True, verbose_name='Критерии задания')),
                ('assignment_deadline', models.DateField(verbose_name='Срок сдачи')),
                ('grading_type', models.CharField(choices=[('points', 'По баллам'), ('pass_fail', 'Зачёт/незачёт')], max_length=20, verbose_name='Тип оценки')),
                ('max_score', models.IntegerField(blank=True, null=True, verbose_name='Максимальный балл')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unireax_main.lecture', verbose_name='Лекция')),
            ],
            options={
                'db_table': 'practical_assignment',
                'verbose_name': 'Практическое задание',
                'verbose_name_plural': 'Практические задания',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Текст вопроса')),
                ('question_score', models.IntegerField(default=1, verbose_name='Балл за вопрос')),
                ('correct_text', models.TextField(blank=True, null=True, verbose_name='Правильный ответ')),
                ('question_order', models.IntegerField(verbose_name='Порядок вопроса')),
                ('answer_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unireax_main.answertype', verbose_name='Тип ответа')),
            ],
            options={
                'db_table': 'question',
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='MatchingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_text', models.TextField(verbose_name='Левый текст')),
                ('right_text', models.TextField(verbose_name='Правый текст')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unireax_main.question', verbose_name='Вопрос')),
            ],
            options={
                'db_table': 'matching_pair',
                'verbose_name': 'Пара соответствия',
                'verbose_name_plural': 'Пары соответствия',
            },
        ),
        migrations.CreateModel(
            name='ChoiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.TextField(verbose_name='Текст варианта')),
                ('is_correct', models.BooleanField(verbose_name='Правильный')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unireax_main.question', verbose_name='Вопрос')),
            ],
            options={
                'db_table': 'choice_option',
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=255, verbose_name='Название теста')),
                ('test_description', models.TextField(blank=True, null=True, verbose_name='Описание теста')),
                ('is_final', models.BooleanField(default=False, verbose_name='Финальный тест')),
                ('max_attempts', models.IntegerField(blank=True, null=True, verbose_name='Максимум попыток')),
                ('grading_form', models.CharField(choices=[('points', 'По баллам'), ('pass_fail', 'Зачёт/незачёт')], max_length=20, verbose_name='Форма оценки')),
                ('passing_score', models.IntegerField(blank=True, null=True, verbose_name='Проходной балл')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unireax_main.lecture', verbose_name='Лекция')),
            ],
            options={
                'db_table': 'test',
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unireax_main.test', verbose_name='Тест'),
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, null=True, verbose_name='Текст ответа')),
                ('answer_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата ответа')),
                ('attempt_number', models.IntegerField(default=1, verbose_name='Номер попытки')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='Балл')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unireax_main.question', verbose_name='Вопрос')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'db_table': 'user_answer',
                'verbose_name': 'Ответ пользователя',
                'verbose_name_plural': 'Ответы пользователей',
                'unique_together': {('user', 'question', 'attempt_number')},
            },
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
                ('status_course', models.BooleanField(default=False, verbose_name='Статус курса')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Дата завершения')),
                ('course_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена курса')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unireax_main.course', verbose_name='Курс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'db_table': 'user_course',
                'verbose_name': 'Пользователь на курсе',
                'verbose_name_plural': 'Пользователи на курсах',
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=255, unique=True, verbose_name='Номер сертификата')),
                ('issue_date', models.DateField(verbose_name='Дата выдачи')),
                ('certificate_file_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='Путь к файлу сертификата')),
                ('user_course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='unireax_main.usercourse', verbose_name='Пользователь на курсе')),
            ],
            options={
                'db_table': 'certificate',
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
            },
        ),
        migrations.CreateModel(
            name='UserPracticalAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_file_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='Путь к файлу сдачи')),
                ('submission_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата сдачи')),
                ('attempt_number', models.IntegerField(default=1, verbose_name='Номер попытки')),
                ('practical_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unireax_main.practicalassignment', verbose_name='Практическое задание')),
                ('submission_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unireax_main.assignmentstatus', verbose_name='Статус сдачи')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'db_table': 'user_practical_assignment',
                'verbose_name': 'Сдача практического задания',
                'verbose_name_plural': 'Сдачи практических заданий',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='Балл')),
                ('is_passed', models.BooleanField(blank=True, null=True, verbose_name='Зачтено')),
                ('comment_feedback', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('user_practical_assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='unireax_main.userpracticalassignment', verbose_name='Сдача задания')),
            ],
            options={
                'db_table': 'feedback',
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратные связи',
            },
        ),
        migrations.CreateModel(
            name='CourseTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала курса')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unireax_main.course', verbose_name='Курс')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
            ],
            options={
                'db_table': 'course_teacher',
                'verbose_name': 'Преподаватель курса',
                'verbose_name_plural': 'Преподаватели курсов',
                'unique_together': {('course', 'teacher')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField(verbose_name='Текст отзыва')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Рейтинг')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('comment_review', models.TextField(blank=True, null=True, verbose_name='Комментарий к отзыву')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unireax_main.course', verbose_name='Курс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'db_table': 'review',
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'unique_together': {('course', 'user')},
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата завершения')),
                ('final_score', models.IntegerField(blank=True, null=True, verbose_name='Итоговый балл')),
                ('is_passed', models.BooleanField(blank=True, null=True, verbose_name='Зачтено')),
                ('attempt_number', models.IntegerField(default=1, verbose_name='Номер попытки')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unireax_main.test', verbose_name='Тест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'db_table': 'test_result',
                'verbose_name': 'Результат теста',
                'verbose_name_plural': 'Результаты тестов',
                'unique_together': {('user', 'test', 'attempt_number')},
            },
        ),
        migrations.CreateModel(
            name='UserMatchingAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_selected_right_text', models.TextField(verbose_name='Выбранный правый текст')),
                ('matching_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unireax_main.matchingpair', verbose_name='Пара соответствия')),
                ('user_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unireax_main.useranswer', verbose_name='Ответ пользователя')),
            ],
            options={
                'db_table': 'user_matching_answer',
                'verbose_name': 'Ответ на сопоставление',
                'verbose_name_plural': 'Ответы на сопоставления',
                'unique_together': {('user_answer', 'matching_pair')},
            },
        ),
        migrations.CreateModel(
            name='UserSelectedChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unireax_main.choiceoption', verbose_name='Выбранный вариант')),
                ('user_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unireax_main.useranswer', verbose_name='Ответ пользователя')),
            ],
            options={
                'db_table': 'user_selected_choice',
                'verbose_name': 'Выбранный вариант',
                'verbose_name_plural': 'Выбранные варианты',
                'unique_together': {('user_answer', 'choice_option')},
            },
        ),
    ]