# Generated by Django 5.2.5 on 2025-09-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unireax_main', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='educational_institution',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Учебное заведение'),
        ),
    ]
