# Generated by Django 5.2.5 on 2025-10-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unireax_main', '0003_alter_user_educational_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_photo_path',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Фото курса'),
        ),
    ]
