# Generated by Django 5.2.5 on 2025-10-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unireax_main', '0004_alter_course_course_photo_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='certificat_from_the_place_of_work_path',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='', verbose_name='Путь к файлу справки с места работы'),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Полное название должности по месту работы'),
        ),
    ]
