# Generated by Django 5.2.5 on 2025-10-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unireax_main', '0005_user_certificat_from_the_place_of_work_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewCourseLectures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('course_name', models.CharField(max_length=255)),
                ('lecture_id', models.IntegerField()),
                ('lecture_name', models.CharField(max_length=255)),
                ('lecture_content', models.TextField()),
                ('lecture_document_path', models.CharField(max_length=255, null=True)),
                ('lecture_order', models.IntegerField()),
            ],
            options={
                'db_table': 'view_course_lectures',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewCoursePracticalAssignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('course_name', models.CharField(max_length=255)),
                ('lecture_id', models.IntegerField()),
                ('lecture_name', models.CharField(max_length=255)),
                ('practical_assignment_id', models.IntegerField()),
                ('practical_assignment_name', models.CharField(max_length=255)),
                ('practical_assignment_description', models.TextField()),
                ('assignment_document_path', models.CharField(max_length=255, null=True)),
                ('assignment_criteria', models.TextField(null=True)),
                ('assignment_deadline', models.DateField()),
                ('grading_type', models.CharField(max_length=20)),
                ('max_score', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'view_course_practical_assignments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewCourseTests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('course_name', models.CharField(max_length=255)),
                ('lecture_id', models.IntegerField()),
                ('lecture_name', models.CharField(max_length=255)),
                ('test_id', models.IntegerField()),
                ('test_name', models.CharField(max_length=255)),
                ('test_description', models.TextField(null=True)),
                ('is_final', models.BooleanField()),
                ('max_attempts', models.IntegerField(null=True)),
                ('grading_form', models.CharField(max_length=20)),
                ('passing_score', models.IntegerField(null=True)),
                ('question_id', models.IntegerField()),
                ('question_text', models.TextField()),
                ('answer_type_id', models.IntegerField()),
                ('answer_type_name', models.CharField(max_length=50)),
                ('question_score', models.IntegerField()),
                ('correct_text', models.TextField(null=True)),
                ('question_order', models.IntegerField()),
                ('choice_option_id', models.IntegerField(null=True)),
                ('option_text', models.TextField(null=True)),
                ('is_correct', models.BooleanField(null=True)),
                ('matching_pair_id', models.IntegerField(null=True)),
                ('left_text', models.TextField(null=True)),
                ('right_text', models.TextField(null=True)),
            ],
            options={
                'db_table': 'view_course_tests',
                'managed': False,
            },
        ),
    ]
