# Generated by Django 5.2.5 on 2025-10-27 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unireax_main', '0006_viewcourselectures_viewcoursepracticalassignments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активность курса'),
        ),
        migrations.AddField(
            model_name='courseteacher',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активность преподавателя на курсе'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активность лекции'),
        ),
        migrations.AddField(
            model_name='practicalassignment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активность практического задания'),
        ),
        migrations.AddField(
            model_name='test',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активность теста'),
        ),
        migrations.AddField(
            model_name='usercourse',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активность слушателя на курсе'),
        ),
    ]
