# Generated by Django 5.2.5 on 2025-11-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unireax_main', '0008_course_is_active_courseteacher_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='patronymic',
            field=models.CharField(blank=True, max_length=35, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='educational_institution',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Учебное заведение'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Полное название должности по месту работы'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_theme',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Цветовая тема приложения пользователя'),
        ),
    ]
