# Generated by Django 5.2.5 on 2025-11-02 18:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unireax_main', '0009_user_patronymic_alter_user_educational_institution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='certificat_from_the_place_of_work_path',
            field=models.FileField(blank=True, help_text='Форматы: JPG, PNG, PDF. Максимальный размер: 10 МБ', max_length=255, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])], verbose_name='Справка с места работы'),
        ),
    ]
