# Generated by Django 5.2.5 on 2025-11-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unireax_main', '0011_alter_course_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='patronymic',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Отчество'),
        ),
    ]
