# Generated by Django 5.2.5 on 2025-11-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unireax_main', '0012_alter_user_patronymic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_text',
            field=models.TextField(verbose_name='Текст отзывы'),
        ),
        migrations.AlterModelTable(
            name='answertype',
            table='answer_type',
        ),
        migrations.AlterModelTable(
            name='assignmentstatus',
            table='assignment_status',
        ),
        migrations.AlterModelTable(
            name='certificate',
            table='certificate',
        ),
        migrations.AlterModelTable(
            name='choiceoption',
            table='choice_option',
        ),
        migrations.AlterModelTable(
            name='course',
            table='course',
        ),
        migrations.AlterModelTable(
            name='coursecategory',
            table='course_category',
        ),
        migrations.AlterModelTable(
            name='courseteacher',
            table='course_teacher',
        ),
        migrations.AlterModelTable(
            name='coursetype',
            table='course_type',
        ),
        migrations.AlterModelTable(
            name='feedback',
            table='feedback',
        ),
        migrations.AlterModelTable(
            name='lecture',
            table='lecture',
        ),
        migrations.AlterModelTable(
            name='matchingpair',
            table='matching_pair',
        ),
        migrations.AlterModelTable(
            name='practicalassignment',
            table='practical_assignment',
        ),
        migrations.AlterModelTable(
            name='question',
            table='question',
        ),
        migrations.AlterModelTable(
            name='review',
            table='review',
        ),
        migrations.AlterModelTable(
            name='role',
            table='role',
        ),
        migrations.AlterModelTable(
            name='test',
            table='test',
        ),
        migrations.AlterModelTable(
            name='testresult',
            table='test_result',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.AlterModelTable(
            name='useranswer',
            table='user_answer',
        ),
        migrations.AlterModelTable(
            name='usercourse',
            table='user_course',
        ),
        migrations.AlterModelTable(
            name='usermatchinganswer',
            table='user_matching_answer',
        ),
        migrations.AlterModelTable(
            name='userpracticalassignment',
            table='user_practical_assignment',
        ),
        migrations.AlterModelTable(
            name='userselectedchoice',
            table='user_selected_choice',
        ),
    ]
