# Generated by Django 5.2.5 on 2025-11-07 12:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unireax_main', '0015_alter_course_course_photo_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_photo_path',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Фото курса'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='lecture_document_path',
            field=models.FileField(blank=True, null=True, upload_to='lectures/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])], verbose_name='Документ лекции'),
        ),
        migrations.AlterField(
            model_name='practicalassignment',
            name='assignment_document_path',
            field=models.FileField(blank=True, null=True, upload_to='assignments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])], verbose_name='Документ задания'),
        ),
        migrations.AlterField(
            model_name='user',
            name='certificat_from_the_place_of_work_path',
            field=models.FileField(blank=True, help_text='Форматы: JPG, PNG, PDF. Максимальный размер: 10 МБ', max_length=255, null=True, upload_to='certificates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])], verbose_name='Справка с места работы'),
        ),
    ]
