# Generated by Django 5.2.5 on 2025-11-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unireax_main', '0016_alter_course_course_photo_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicalassignment',
            name='assignment_deadline',
            field=models.DateTimeField(verbose_name='Срок сдачи'),
        ),
    ]
