# Generated by Django 5.2.5 on 2025-11-16 12:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unireax_main', '0017_alter_practicalassignment_assignment_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewAssignmentSubmissions',
            fields=[
                ('submission_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('user_name', models.CharField(max_length=255)),
                ('practical_assignment_id', models.BigIntegerField()),
                ('practical_assignment_name', models.CharField(max_length=255)),
                ('lecture_name', models.CharField(max_length=255)),
                ('course_name', models.CharField(max_length=255)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('attempt_number', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
                ('comment', models.TextField(blank=True, null=True)),
                ('file_count', models.IntegerField()),
                ('total_size', models.BigIntegerField()),
            ],
            options={
                'db_table': 'view_assignment_submissions',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='userpracticalassignment',
            name='submission_file_path',
        ),
        migrations.AddField(
            model_name='userpracticalassignment',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к сдаче'),
        ),
        migrations.CreateModel(
            name='AssignmentSubmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='assignment_submissions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'zip'])], verbose_name='Файл сдачи')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('file_name', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('file_size', models.BigIntegerField(verbose_name='Размер файла')),
                ('user_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unireax_main.userpracticalassignment', verbose_name='Сдача задания')),
            ],
            options={
                'verbose_name': 'Файл сдачи задания',
                'verbose_name_plural': 'Файлы сдачи заданий',
                'db_table': 'assignment_submission_file',
            },
        ),
    ]
