# Generated by Django 5.2.5 on 2025-11-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unireax_main', '0020_passwordresetcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicalassignment',
            name='assignment_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок сдачи'),
        ),
    ]
