# Generated by Django 5.2.5 on 2025-11-23 15:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unireax_main', '0022_trigger_and_function_for_complete_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseteacher',
            name='start_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата начала курса'),
        ),
    ]
