# Generated by Django 5.2.5 on 2025-11-24 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unireax_main', '0023_alter_courseteacher_start_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewassignmentsubmissions',
            options={'managed': False, 'verbose_name': 'Представление: сданная практическая работа', 'verbose_name_plural': 'Представление: сданные практические работы'},
        ),
        migrations.AlterModelOptions(
            name='viewcourselectures',
            options={'managed': False, 'verbose_name': 'Представление: лекция', 'verbose_name_plural': 'Представление: лекции'},
        ),
        migrations.AlterModelOptions(
            name='viewcoursepracticalassignments',
            options={'managed': False, 'verbose_name': 'Представление: практическая работа', 'verbose_name_plural': 'Представление: практические работы'},
        ),
        migrations.AlterModelOptions(
            name='viewcoursetests',
            options={'managed': False, 'verbose_name': 'Представление: тест', 'verbose_name_plural': 'Представление: тесты'},
        ),
    ]
