# Generated by Django 5.2.5 on 2025-11-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unireax_main', '0025_update_course_progress_func'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты'),
        ),
    ]
