# Generated by Django 5.2.5 on 2025-11-26 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unireax_main', '0026_alter_usercourse_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='certificat_from_the_place_of_work_path',
            field=models.FileField(blank=True, help_text='Форматы: JPG, PNG, PDF. Максимальный размер: 10 МБ', max_length=255, null=True, upload_to='certificates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])], verbose_name='Справка с места работы/документ об образовании'),
        ),
    ]
