# Generated by Django 5.2.5 on 2025-11-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unireax_main', '0027_alter_user_certificat_from_the_place_of_work_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecategory',
            name='course_category_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название категории курса'),
        ),
        migrations.AlterField(
            model_name='coursetype',
            name='course_type_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название типа курса'),
        ),
    ]
