"""
Django settings for unireax_root project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os


YOOKASSA_SHOP_ID = '1208337' 
YOOKASSA_SECRET_KEY = 'test_A-k7wgc_JHbdEvEIGcb2N_BfhZIzpcWvoBXqglWqLPk' 


MULTIPROC_DIR = str(Path(__file__).resolve().parent.parent / "prometheus_metrics")
os.makedirs(MULTIPROC_DIR, exist_ok=True)
os.environ["PROMETHEUS_MULTIPROC_DIR"] = MULTIPROC_DIR


import os
from dotenv import load_dotenv
dotenv_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), '.env')
if os.path.exists(dotenv_path):
    load_dotenv(dotenv_path)


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-a43bly_hpjt_z2h5q%yjhc#nzeu=-k+-+3lp=&=p%i%c0k%ic9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'unireax_main',
    'django_prometheus',
    'rest_framework',
    'api_unireax'
]

MIDDLEWARE = [
    'django_prometheus.middleware.PrometheusBeforeMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'unireax_main.utils.middleware.RequestMiddleware', 
    'django_prometheus.middleware.PrometheusAfterMiddleware',
]

ROOT_URLCONF = 'unireax_root.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'unireax_main.context_processors.theme_context'
            ],
        },
    },
]

WSGI_APPLICATION = 'unireax_root.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


# основная тестовая
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'HOST': '127.0.0.1',
        'PORT': '5432',
        'NAME': 'testkurs3',
        'USER': 'postgres',
        'PASSWORD': '1'
    }
}



# механизм для хэширования пароля 
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
]
    
# переопределение модели пользователя в бд (для кастомной с добавлением полей)
AUTH_USER_MODEL = 'unireax_main.User'


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.mail.ru'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'unireax@mail.ru' 
EMAIL_HOST_PASSWORD = '5E97EMcBvD4fWGScg8HD'  # пароль приложения
DEFAULT_FROM_EMAIL = 'unireax@mail.ru'  # email отправителя
BASE_URL = 'http://127.0.0.1:8000' 
SITE_URL = BASE_URL 

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static")
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators



AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
      {
        'NAME': 'unireax_root.validators.UppercaseValidator',
    },
    {
        'NAME': 'unireax_root.validators.SpecialCharacterValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru-RU'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True

# настройки для аутентификации
LOGIN_URL = '/auth/'
LOGIN_REDIRECT_URL = '/profile/'
LOGOUT_REDIRECT_URL = '/'

# правильный формат даты для апи
REST_FRAMEWORK = {
    'DATETIME_FORMAT' : "%Y-%m-%d %H:%M:%S.%f%z",
    'EXCEPTION_HANDLER': 'api_unireax.api_exceptions.custom_exception_handler',
}

CSRF_FAILURE_VIEW = 'unireax_main.views.custom_csrf_failure'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# суперпользователь для начальной настройки (initial_setup.py)
DJANGO_SUPERUSER_USERNAME = os.environ.get('DJANGO_SUPERUSER_USERNAME', 'admin')
DJANGO_SUPERUSER_EMAIL = os.environ.get('DJANGO_SUPERUSER_EMAIL', 'admin@example.com')
DJANGO_SUPERUSER_PASSWORD = os.environ.get('DJANGO_SUPERUSER_PASSWORD', 'User123456!')

# настройки безопасности для начальной настройки админа
DJANGO_SUPERUSER_MIN_PASSWORD_LENGTH = int(os.environ.get('DJANGO_SUPERUSER_MIN_PASSWORD_LENGTH', 8))
DJANGO_SUPERUSER_REQUIRE_STRONG_PASSWORD = os.environ.get('DJANGO_SUPERUSER_REQUIRE_STRONG_PASSWORD', 'True').lower() == 'true'

# список слабых паролей, которые следует запретить
DJANGO_SUPERUSER_WEAK_PASSWORDS = [
    'admin', 'password', '12345678', 'qwerty', 'qwerty123', '123'
]


# настройки сессий и куки
SESSION_COOKIE_AGE = 1209600  
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = False  # позже поменяю на true для HTTPS
CSRF_COOKIE_SECURE = False

# для избранного через куки
FAVORITES_COOKIE_NAME = 'user_favorites'
FAVORITES_COOKIE_AGE = 31536000 



handler404 = 'unireax_main.views.custom_404'
handler500 = 'unireax_main.views.custom_500'
handler403 = 'unireax_main.views.custom_403'


# influxdb
INFLUXDB_URL = os.getenv('INFLUXDB_URL', 'http://localhost:8766')
INFLUXDB_TOKEN = os.getenv('INFLUXDB_TOKEN', 'nSSuuLsy8eQ87-YQsC47wSoWAUF0rWayVUtQKNcYaNrbGC2qpbkc6jjuQPKqI1BjYq5hIbxS3QAyhD5CptC16Q==')
INFLUXDB_ORG = os.getenv('INFLUXDB_ORG', 'MPT')
INFLUXDB_BUCKET = os.getenv('INFLUXDB_BUCKET', 'metrics')